name: MoneyakMenu
main: sm.main
author: DevTec, _ItsRajsko_
depend: [TheAPI, PlaceholderAPI]
softdepend: [ServerControlReloaded]
api-version: 1.13
version: 1.0
commands:
  menu:
  moneyakmenu:
    aliases: [mmenu]